name: Deploy EC2 Server
on: pull_request
env:
  VERSION: ${{ github.sha }}
#on:
#  push:
#    branches:
#      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Jib Task
        run: ./gradlew :rendezvous-rest:jib
  deploy:
    runs-on: self-hosted
    steps:
      - name: Docker Login
        run: aws ecr get-login-password --region ap-northeast-2 | sudo docker login --username AWS --password-stdin 564549038106.dkr.ecr.ap-northeast-2.amazonaws.com/
      - name: Docker run
        run: |
          sudo docker stop rendezvous-app
          sudo docker rm rendezvous-app
          sudo docker rmi -f ${{ secrets.IMAGE_REPOSITORY }}:latest
          sudo docker pull ${{ secrets.IMAGE_REPOSITORY }}:latest
          sudo docker run -p 80:8080 --name rendezvous-app ${{ secrets.IMAGE_REPOSITORY }}:latest